### ISSUE TITLE
SOME WIKI IMPROVEMENTS for 2.2

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/info_foundation_archive#282]
## Deliverables

- [x] Get Team data dynamic again (issue #62)
    - We used to have team data dynamically imported from the data_team repo. Let's bring this back as that is the most accurate representation of our team & is up to date.
- [x] Rename all SDK instances (issue #94)
    - We need to replace all 3SDK/SDK mentions to TF Grid manual / grid_manual.threefold.io
- [x] Change all htmls on wiki into the right markdown codes (issue #246)
    - the right code for images should be:  ! [] (./img/filename.png)
instead of: < img src >
- [ ] Check all the links throughout the whole wiki
- [x] Check spelling throughout the whole wiki (issue #125)

**Comment by VonSub** [comment]
closing this is more than a few itterations ago.
